name: PR to Develop

on:
  workflow_dispatch:
  pull_request:
    branches: [ develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.x'

    - name: Restore
      run: dotnet restore ./DevsBank.sln
        
    - name: Build
      run: dotnet build ./DevsBank.sln --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal